insert into ACCOUNT (account_id, attribute, morm, name) values (1, '', '', 'AC1')
insert into ACCOUNT (account_id, attribute, morm, name) values (2, '', '', 'AC2')
insert into ACCOUNT (account_id, attribute, morm, name) values (3, '', '', 'AC3')
insert into ACCOUNT (account_id, attribute, morm, name) values (4, '', '', 'AC4')
insert into ACCOUNT (account_id, attribute, morm, name) values (5, '', '', 'AC5')
insert into ACCOUNT (account_id, attribute, morm, name) values (6, '', '', 'AC6')
insert into ACCOUNT (account_id, attribute, morm, name) values (7, '', '', 'AC7')
insert into ACCOUNT (account_id, attribute, morm, name) values (8, '', '', 'AC8')
insert into ACCOUNT (account_id, attribute, morm, name) values (9, '', '', 'AC9')

insert into MEASURE (measure_id, measure_name) values (1, 'Value')
insert into MEASURE (measure_id, measure_name) values (2, 'Amount')
insert into MEASURE (measure_id, measure_name) values (3, 'Input')
insert into MEASURE (measure_id, measure_name) values (4, 'Review')

insert into PERIOD (period_id, period_name) values (1, 'P0')
insert into PERIOD (period_id, period_name) values (2, 'P1')
insert into PERIOD (period_id, period_name) values (3, 'P0-P9')
insert into PERIOD (period_id, period_name) values (4, 'P1-P9')

insert into SCENARIO (scenario_id, scenario_name) values (1, 'BHC')
insert into SCENARIO (scenario_id, scenario_name) values (2, 'BHCSA')
insert into SCENARIO (scenario_id, scenario_name) values (3, 'FRB')
insert into SCENARIO (scenario_id, scenario_name) values (4, 'FRBSA')


insert into ELEMENT(element_id,element_type,element_value) values(11,'Scenario','BHC BASE')
insert into ELEMENT(element_id,element_type,element_value) values(2,'Scenario','BHC SA')
insert into ELEMENT(element_id,element_type,element_value) values(3,'Scenario','FRB BASE')
insert into ELEMENT(element_id,element_type,element_value) values(4,'Scenario','FRB SA')
insert into ELEMENT(element_id,element_type,element_value) values(5,'Period','P0')
insert into ELEMENT(element_id,element_type,element_value) values(6,'Period','P0-P9')
insert into ELEMENT(element_id,element_type,element_value) values(7,'Period','P1-P9')
insert into ELEMENT(element_id,element_type,element_value) values(8,'Measure','Value')
insert into ELEMENT(element_id,element_type,element_value) values(9,'Measure','Input Reviewer')
insert into ELEMENT(element_id,element_type,element_value) values(10,'Measure','Attestation Reviewer')